accounts/urls.py
from django.urls import include, path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'account/',
        include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'change/',
                views.AccountChangeView.as_view(),
                name='account_change'
            ),
            path(
                'login/',
                views.LoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.LogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                views.PasswordChangeView.as_view(),
                name='account_password_change'
            ),
            path(
                'password-reset/',
                views.PasswordResetView.as_view(),
                name='account_password_reset'
            ),
            path(
                'password-reset/done/',
                views.PasswordResetDoneView.as_view(),
                name='account_password_reset_done'
            ),
            path(
                'password-reset/<uidb64>/<token>/',
                views.PasswordResetConfirmView.as_view(),
                name='account_password_reset_confirm'
            ),
            path(
                'password-reset/complete/',
                views.PasswordResetCompleteView.as_view(),
                name='account_password_reset_complete'
            ),
        ])
    ),
]

panel/urls.py
from panel.views.phone import PhoneConnectView
from django.urls import include, path

from . import views


app_name = 'panel'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'account/',
        include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'change/',
                views.AccountChangeView.as_view(),
                name='account_change'
            ),
            path(
                'login/',
                views.LoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.LogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                views.PasswordChangeView.as_view(),
                name='account_password_change'
            ),
            path(
                'password-reset/',
                views.PasswordResetView.as_view(),
                name='account_password_reset'
            ),
            path(
                'password-reset/done/',
                views.PasswordResetDoneView.as_view(),
                name='account_password_reset_done'
            ),
            path(
                'password-reset/<uidb64>/<token>/',
                views.PasswordResetConfirmView.as_view(),
                name='account_password_reset_confirm'
            ),
            path(
                'password-reset/complete/',
                views.PasswordResetCompleteView.as_view(),
                name='account_password_reset_complete'
            ),
        ])
    ),
    path(
        'company/',
        views.CompanyCreateView.as_view(),
        name='company_add'
    ),
    path(
        'phones/',
        include([
            path(
                '',
                views.PhoneListView.as_view(),
                name='phone_list'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.PhoneChangeView.as_view(),
                        name='phone_change'
                    ),
                    path(
                        'connect/',
                        views.PhoneConnectView.as_view(),
                        name='phone_connect'
                    ),
                    path(
                        'delete/',
                        views.PhoneDeleteView.as_view(),
                        name='phone_delete'
                    )
                ])
            ),
            path(
                'purchase/',
                views.PhonePurchaseView.as_view(),
                name='phone_purchase'
            ),
            path(
                'search/',
                views.PhoneSearchView.as_view(),
                name='phone_search'
            ),
            path(
                'sync/',
                views.PhoneSyncView.as_view(),
                name='phone_sync'
            )
        ])
    ),
    path(
        'services/',
        include([
            path(
                '',
                views.ServiceListView.as_view(),
                name='service_list'
            ),
            path(
                'add/',
                views.ServiceCreateView.as_view(),
                name='service_add'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.ServiceUpdateView.as_view(),
                        name='service_change'
                    ),
                    path(
                        'delete/',
                        views.ServiceDeleteView.as_view(),
                        name='service_delete'
                    )
                ])
            )
        ])
    ),
    path(
        '<company>/',
        include([
            path(
                '',
                views.IndexView.as_view(),
                name='index'
            ),
            path(
                'add/',
                views.CompanyChildCreateView.as_view(),
                name='company_add'
            ),
            path(
                'change/',
                include([
                    path(
                        '',
                        views.CompanyUpdateView.as_view(),
                        name='company_change'
                    ),
                    path(
                        'messages/',
                        views.CompanyUpdateMessagesView.as_view(),
                        name='company_change_messages'
                    ),
                    path(
                        'links/',
                        views.CompanyUpdateLinksView.as_view(),
                        name='company_change_links'
                    )
                ])
            ),
            path(
                'customers/',
                include([
                    path(
                        '',
                        views.CustomerListView.as_view(),
                        name='customer_list'
                    ),
                    path(
                        'add/',
                        views.CustomerCreateView.as_view(),
                        name='customer_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CustomerDetailView.as_view(),
                                name='customer_detail'
                            ),
                            path(
                                'change/',
                                views.CustomerUpdateView.as_view(),
                                name='customer_change'
                            ),
                            path(
                                'delete/',
                                views.CustomerDeleteView.as_view(),
                                name='customer_delete'
                            ),
                            path(
                                'send-sms/',
                                views.CustomerSendSMSView.as_view(),
                                name='customer_send_sms'
                            )
                        ])
                    ),

                ])
            ),
            path(
                'products/',
                include([
                    path(
                        '',
                        views.ProductListView.as_view(),
                        name='product_list'
                    ),
                    path(
                        'add/',
                        views.ProductCreateView.as_view(),
                        name='product_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.ProductDetailView.as_view(),
                                name='product_detail'
                            ),
                            path(
                                'change/',
                                views.ProductUpdateView.as_view(),
                                name='product_change'
                            ),
                            path(
                                'delete/',
                                views.ProductDeleteView.as_view(),
                                name='product_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'category/',
                include([
                    path(
                        '',
                        views.CategoryListView.as_view(),
                        name='category_list'
                    ),
                    path(
                        'add/',
                        views.CategoryCreateView.as_view(),
                        name='category_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CategoryDetailView.as_view(),
                                name='category_detail'
                            ),
                            path(
                                'change/',
                                views.CategoryUpdateView.as_view(),
                                name='category_change'
                            ),
                            path(
                                'delete/',
                                views.CategoryDeleteView.as_view(),
                                name='category_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'ordenes/',
                include([
                    path(
                        '',
                        views.OrderListView.as_view(),
                        name='order_list'
                    ),
                        ])
            ),
            path(
                'feedbacks/',
                include([
                    path(
                        '',
                        views.FeedbackListView.as_view(),
                        name='feedback_list'
                    ),
                    path(
                        '<int:pk>/',
                        views.FeedbackDetailView.as_view(),
                        name='feedback_detail'
                    )
                ])
            ),
            path(
                'messages/',
                include([

taypa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('taypa.api.urls')),
    path(
        'jsi18n/',
        JavaScriptCatalog.as_view(),
        name='javascript-catalog'
    ),
    path('panel/', include('panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing-profile/', include('billing_profiles.urls')),
    path('', include('public.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler400 = 'panel.views.error.pag_400_bad_request'
handler403 = 'panel.views.error.pag_403_forbidden'
handler404 = 'panel.views.error.pag_404_not_found'
handler500 = 'panel.views.error.pag_500_error_server'

accounts/views/views.py
from django.shortcuts import render

# Create your views here.

panel/views/base.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from core.models import Company
from core.views import CompanyMixin

class IndexView(CompanyMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'panel/index.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            parent_company__isnull=True
        )

        if not self.request.user.is_staff:
            queryset = queryset.none()
        
        return queryset

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff and not self.company:
            queryset = request.user.collaborator_set.filter(
                company__parent_company__isnull=True
            )

            if queryset.count() == 1:
                collaborator = queryset.get()
                company = collaborator.company
                return HttpResponseRedirect(company.get_absolute_url())
                   
        return super().get(request, *args, **kwargs)

panel/views/category.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView, DeleteView, DetailView, UpdateView
)
from django_filters.views import FilterView

from core.models import Category

from core.views import (
    CompanyCreateMixin,
    CompanyQuerySetMixin
)
from ..filters.category import CategoryFilterSet
from ..forms.category import get_category_form

class CategoryCreateView(CompanyCreateMixin, CreateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

class CategoryDeleteView(CompanyQuerySetMixin, DeleteView):
    model = Category
    template_name = 'panel/category/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('panel:category_list', args=[self.company.slug])

class CategoryDetailView(CompanyQuerySetMixin, DetailView):
    model = Category
    template_name = 'panel/category/detail.html'

class CategoryListView(CompanyQuerySetMixin, FilterView):
    template_name = 'panel/category/list.html'
    filterset_class = CategoryFilterSet
    model = Category
    paginate_by = 30
    ordering = ['-id']  
class CategoryUpdateView(CompanyQuerySetMixin, UpdateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

panel/views/company.py
from boilerplate.mixins import ExtraFormsAndFormsetsMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView

from core.models import Company
from core.views import (
    CompanyCreateMixin,
    CollaboratorRequiredMixin,
    UserCreateMixin
)
from ..forms.company import (
    CompanyForm,
    CompanyChildForm,
    CompanyEmptyForm,
    CompanyLinkFormSet,
    CompanyMessagesForm
)

class CompanyCreateView(PermissionRequiredMixin, CreateView):
    form_class = CompanyForm
    model = Company
    permission_required = 'core:add_company'
    template_name = 'panel/company/form.html'

class CompanyChildCreateView(
    CompanyCreateMixin, UserCreateMixin, CreateView
):
    company_field = 'parent_company'
    form_class = CompanyChildForm
    model = Company
    template_name = 'panel/company/form.html'

class CompanyUpdateView(
    CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyChildForm
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

class CompanyUpdateLinksView(
    ExtraFormsAndFormsetsMixin, CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyEmptyForm
    formset_list = (
        CompanyLinkFormSet,
    )
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

class CompanyUpdateMessagesView(
    CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyMessagesForm
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

panel/views/feedback.py
from django.views.generic import DetailView
from django_filters.views import FilterView

from core.views import CompanyQuerySetMixin
from core.models import Feedback
from ..filters.feedback import FeedbackFilterSet


class FeedbackDetailView(CompanyQuerySetMixin, DetailView):
    model = Feedback
    template_name = 'panel/feedback/detail.html'


class FeedbackListView(CompanyQuerySetMixin, FilterView):
    filterset_class = FeedbackFilterSet
    model = Feedback
    paginate_by = 30
    template_name = 'panel/feedback/list.html'

panel/templates/panel/account/detail.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Your account" %}</li>
{% endblock breadcrumb %}

{% block content_inner %}
  <div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{% trans "Your account" %}</h2>
    <div>
      <a class="btn btn-primary" href="{% url 'panel:account_change' %}">{% trans "Change" %}</a>
      <a class="btn btn-primary" href="{% url 'panel:account_password_change' %}">{% trans "Change password" %}</a>
    </div>
  </div>
{% endblock content_inner %}

panel/templates/panel/account/form.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item"><a href="{% url 'panel:account_detail' %}">{% trans "Your account" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Change" %}</li>
{% endblock breadcrumb %}

{% block content_inner %}
  <div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{% trans "Change your account" %}</h2>
  </div>

  {% include 'panel/_snippets/form.html' with layout="horizontal" %}
{% endblock content_inner %}

panel/templates/panel/account/layout.html
{% extends 'panel/layout.html' %}

{% block title %}{{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
<div class="container vh-100">
  <div class="align-items-center d-flex justify-content-center h-100">
    <div class="col-12 col-sm-10 col-md-6 col-lg-4 text-center">
      <div class="card">
        <div class="card-body">
          {% block content_inner %}{% endblock content_inner %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

panel/templates/panel/account/logged_out.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block content_inner %}
  <p>{% translate "Thanks for spending some quality time with the Web site today." %}</p>

  <a class="btn btn-block btn-primary" href="{% url 'panel:account_login' %}">{% translate 'Log in again' %}</a>
{% endblock content_inner %}

panel/templates/panel/account/login.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block title %}{% trans "Login" %}{{ block.super }}{% endblock title %}

{% block content_inner %}
  {% trans "Login" as submit_text %}
  {% include 'panel/_snippets/form.html' %}

  <a class="btn btn-link btn-block" href="{% url 'panel:account_password_reset' %}">{% trans "Password reset" %}</a>
{% endblock content_inner %}

panel/templates/panel/account/password_change.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
<li class="breadcrumb-item"><a href="{% url 'panel:account_detail' %}">{% trans "Your account" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Password change" %}</li>
{% endblock breadcrumb %}


{% block content_inner %}
  <div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{% trans "Password change" %}</h2>
  </div>

  {% include 'panel/_snippets/form.html' with layout="horizontal" %}
{% endblock content_inner %}

panel/templates/panel/account/password_reset_complete.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block content_inner %}
  <p>{% translate "Your password has been set.  You may go ahead and log in now." %}</p>

  <a class="btn btn-primary btn-block" href="{% url 'panel:account_login' %}">{% trans "Login" %}</a>
{% endblock content_inner %}

panel/templates/panel/account/password_reset_confirm.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block content_inner %}
  {% if validlink %}
    <p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>
    {% trans "Change my password" as submit_text %}
    {% include 'panel/_snippets/form.html' %}
  {% else %}
    <p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>
  {% endif %}
{% endblock content_inner %}

panel/templates/panel/account/password_reset_done.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block content_inner %}
  <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

  <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

  <a class="btn btn-primary btn-block" href="{% url 'panel:account_login' %}">{% trans "Login" %}</a>
{% endblock content_inner %}

panel/templates/panel/account/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'panel:account_password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

panel/templates/panel/account/password_reset_form.html
{% extends 'panel/account/layout.html' %}

{% load i18n %}

{% block content_inner %}
  <p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>

  {% trans "Reset my password" as submit_text %}
  {% include 'panel/_snippets/form.html' %}

  <a class="btn btn-link btn-block" href="{% url 'panel:account_login' %}">{% trans "Login" %}</a>
{% endblock content_inner %}