accounts/urls.py
from django.urls import include, path

from . import views

app_name = 'accounts'

urlpatterns = [
    path(
        'account/',
        include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'change/',
                views.AccountChangeView.as_view(),
                name='account_change'
            ),
            path(
                'login/',
                views.LoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.LogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                views.PasswordChangeView.as_view(),
                name='account_password_change'
            ),
            path(
                'password-reset/',
                views.PasswordResetView.as_view(),
                name='account_password_reset'
            ),
            path(
                'password-reset/done/',
                views.PasswordResetDoneView.as_view(),
                name='account_password_reset_done'
            ),
            path(
                'password-reset/<uidb64>/<token>/',
                views.PasswordResetConfirmView.as_view(),
                name='account_password_reset_confirm'
            ),
            path(
                'password-reset/complete/',
                views.PasswordResetCompleteView.as_view(),
                name='account_password_reset_complete'
            ),
        ])
    ),
]

panel/urls.py
from panel.views.phone import PhoneConnectView
from django.urls import include, path

from . import views


app_name = 'panel'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'account/',
        include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'change/',
                views.AccountChangeView.as_view(),
                name='account_change'
            ),
            path(
                'login/',
                views.LoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.LogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                views.PasswordChangeView.as_view(),
                name='account_password_change'
            ),
            path(
                'password-reset/',
                views.PasswordResetView.as_view(),
                name='account_password_reset'
            ),
            path(
                'password-reset/done/',
                views.PasswordResetDoneView.as_view(),
                name='account_password_reset_done'
            ),
            path(
                'password-reset/<uidb64>/<token>/',
                views.PasswordResetConfirmView.as_view(),
                name='account_password_reset_confirm'
            ),
            path(
                'password-reset/complete/',
                views.PasswordResetCompleteView.as_view(),
                name='account_password_reset_complete'
            ),
        ])
    ),
    path(
        'company/',
        views.CompanyCreateView.as_view(),
        name='company_add'
    ),
    path(
        'phones/',
        include([
            path(
                '',
                views.PhoneListView.as_view(),
                name='phone_list'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.PhoneChangeView.as_view(),
                        name='phone_change'
                    ),
                    path(
                        'connect/',
                        views.PhoneConnectView.as_view(),
                        name='phone_connect'
                    ),
                    path(
                        'delete/',
                        views.PhoneDeleteView.as_view(),
                        name='phone_delete'
                    )
                ])
            ),
            path(
                'purchase/',
                views.PhonePurchaseView.as_view(),
                name='phone_purchase'
            ),
            path(
                'search/',
                views.PhoneSearchView.as_view(),
                name='phone_search'
            ),
            path(
                'sync/',
                views.PhoneSyncView.as_view(),
                name='phone_sync'
            )
        ])
    ),
    path(
        'services/',
        include([
            path(
                '',
                views.ServiceListView.as_view(),
                name='service_list'
            ),
            path(
                'add/',
                views.ServiceCreateView.as_view(),
                name='service_add'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.ServiceUpdateView.as_view(),
                        name='service_change'
                    ),
                    path(
                        'delete/',
                        views.ServiceDeleteView.as_view(),
                        name='service_delete'
                    )
                ])
            )
        ])
    ),
    path(
        '<company>/',
        include([
            path(
                '',
                views.IndexView.as_view(),
                name='index'
            ),
            path(
                'add/',
                views.CompanyChildCreateView.as_view(),
                name='company_add'
            ),
            path(
                'change/',
                include([
                    path(
                        '',
                        views.CompanyUpdateView.as_view(),
                        name='company_change'
                    ),
                    path(
                        'messages/',
                        views.CompanyUpdateMessagesView.as_view(),
                        name='company_change_messages'
                    ),
                    path(
                        'links/',
                        views.CompanyUpdateLinksView.as_view(),
                        name='company_change_links'
                    )
                ])
            ),
            path(
                'customers/',
                include([
                    path(
                        '',
                        views.CustomerListView.as_view(),
                        name='customer_list'
                    ),
                    path(
                        'add/',
                        views.CustomerCreateView.as_view(),
                        name='customer_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CustomerDetailView.as_view(),
                                name='customer_detail'
                            ),
                            path(
                                'change/',
                                views.CustomerUpdateView.as_view(),
                                name='customer_change'
                            ),
                            path(
                                'delete/',
                                views.CustomerDeleteView.as_view(),
                                name='customer_delete'
                            ),
                            path(
                                'send-sms/',
                                views.CustomerSendSMSView.as_view(),
                                name='customer_send_sms'
                            )
                        ])
                    ),

                ])
            ),
            path(
                'products/',
                include([
                    path(
                        '',
                        views.ProductListView.as_view(),
                        name='product_list'
                    ),
                    path(
                        'add/',
                        views.ProductCreateView.as_view(),
                        name='product_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.ProductDetailView.as_view(),
                                name='product_detail'
                            ),
                            path(
                                'change/',
                                views.ProductUpdateView.as_view(),
                                name='product_change'
                            ),
                            path(
                                'delete/',
                                views.ProductDeleteView.as_view(),
                                name='product_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'category/',
                include([
                    path(
                        '',
                        views.CategoryListView.as_view(),
                        name='category_list'
                    ),
                    path(
                        'add/',
                        views.CategoryCreateView.as_view(),
                        name='category_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CategoryDetailView.as_view(),
                                name='category_detail'
                            ),
                            path(
                                'change/',
                                views.CategoryUpdateView.as_view(),
                                name='category_change'
                            ),
                            path(
                                'delete/',
                                views.CategoryDeleteView.as_view(),
                                name='category_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'ordenes/',
                include([
                    path(
                        '',
                        views.OrderListView.as_view(),
                        name='order_list'
                    ),
                        ])
            ),
            path(
                'feedbacks/',
                include([
                    path(
                        '',
                        views.FeedbackListView.as_view(),
                        name='feedback_list'
                    ),
                    path(
                        '<int:pk>/',
                        views.FeedbackDetailView.as_view(),
                        name='feedback_detail'
                    )
                ])
            ),
            path(
                'messages/',
                include([

taypa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('taypa.api.urls')),
    path(
        'jsi18n/',
        JavaScriptCatalog.as_view(),
        name='javascript-catalog'
    ),
    path('panel/', include('panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing-profile/', include('billing_profiles.urls')),
    path('', include('public.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler400 = 'panel.views.error.pag_400_bad_request'
handler403 = 'panel.views.error.pag_403_forbidden'
handler404 = 'panel.views.error.pag_404_not_found'
handler500 = 'panel.views.error.pag_500_error_server'

core/models/link.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Link(models.Model):
    company = models.ForeignKey(
        'core.Company', on_delete=models.CASCADE, verbose_name=_("Company")
    )
    service = models.ForeignKey(
        'core.Service', on_delete=models.PROTECT, verbose_name=_("Service")
    )
    icon = models.ImageField(
        blank=True, null=True, upload_to='icon/', verbose_name=_("Icon")
    )
    name = models.CharField(
        blank=True, max_length=100, null=True, verbose_name=_("Name")
    )
    url = models.URLField(
        verbose_name=_("URL")
    )
    order = models.PositiveIntegerField(
        default=0, verbose_name=_("Order")
    )

    class Meta:
        ordering = ['order', 'service']
        unique_together = ('company', 'service')
        verbose_name = _("Link")
        verbose_name_plural = _("Links")

    def __str__(self):
        return str(self.name) if self.name else str(self.service)

panel/views/base.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from core.models import Company
from core.views import CompanyMixin

class IndexView(CompanyMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'panel/index.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            parent_company__isnull=True
        )

        if not self.request.user.is_staff:
            queryset = queryset.none()
        
        return queryset

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff and not self.company:
            queryset = request.user.collaborator_set.filter(
                company__parent_company__isnull=True
            )

            if queryset.count() == 1:
                collaborator = queryset.get()
                company = collaborator.company
                return HttpResponseRedirect(company.get_absolute_url())
                   
        return super().get(request, *args, **kwargs)

panel/views/category.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView, DeleteView, DetailView, UpdateView
)
from django_filters.views import FilterView

from core.models import Category

from core.views import (
    CompanyCreateMixin,
    CompanyQuerySetMixin
)
from ..filters.category import CategoryFilterSet
from ..forms.category import get_category_form

class CategoryCreateView(CompanyCreateMixin, CreateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

class CategoryDeleteView(CompanyQuerySetMixin, DeleteView):
    model = Category
    template_name = 'panel/category/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('panel:category_list', args=[self.company.slug])

class CategoryDetailView(CompanyQuerySetMixin, DetailView):
    model = Category
    template_name = 'panel/category/detail.html'

class CategoryListView(CompanyQuerySetMixin, FilterView):
    template_name = 'panel/category/list.html'
    filterset_class = CategoryFilterSet
    model = Category
    paginate_by = 30
    ordering = ['-id']  
class CategoryUpdateView(CompanyQuerySetMixin, UpdateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

panel/views/error.py
from django.shortcuts import render

#400: peticion invalida
def pag_400_bad_request(request, exception):
    response = render(request, '400.html')
    response.status_code=400
    return response

#403: peticion prohibida
def pag_403_forbidden(request, exception):
    response = render(request, '403.html')
    response.status_code=403
    return response

#404: página no encontrada
def pag_404_not_found(request, exception):
    response = render(request, '404.html')
    response.status_code = 404
    return response

#500: error en el servidor
def pag_500_error_server(request):
    response = render(request, '500.html')
    response.status_code=500
    return response

panel/views/feedback.py
from django.views.generic import DetailView
from django_filters.views import FilterView

from core.views import CompanyQuerySetMixin
from core.models import Feedback
from ..filters.feedback import FeedbackFilterSet


class FeedbackDetailView(CompanyQuerySetMixin, DetailView):
    model = Feedback
    template_name = 'panel/feedback/detail.html'


class FeedbackListView(CompanyQuerySetMixin, FilterView):
    filterset_class = FeedbackFilterSet
    model = Feedback
    paginate_by = 30
    template_name = 'panel/feedback/list.html'

panel/templates/panel/index.html
{% extends 'panel/layout.html' %}

{% load bootstrap4 i18n %}

{% block content %}

{% block navigation %}
  <nav class="mb-3 navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% if company %}{% url 'panel:index' company.slug %}{% else %}{% url 'panel:index' %}{% endif %}">{% if company %}{{ company }}{% else %}Taypa!{% endif %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain"
      aria-controls="navbarMain" aria-expanded="false" aria-label="{% trans "Toggle navigation" %}">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto">
        {% if company %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'panel:product_list' company.slug %}">{% trans "Products" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'panel:category_list' company.slug %}">{% trans "Categories" %}</a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:customer_list' company.slug %}">{% trans "Customers" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:feedback_list' company.slug %}">{% trans "Feedbacks" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:message_list' company.slug %}">{% trans "Messages" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:user_list' company.slug %}">{% trans "Users" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:order_list' company.slug %}">{% trans "Ordenes" %}</a>
          </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav my-2 my-lg-0">
        {% if company %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarCompany" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-cog"></i>
            </a>

            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarCompany">
              <a class="dropdown-item" href="{% url 'panel:company_change' company.slug %}">{% trans "Update company" %}</a>
              <a class="dropdown-item" href="{% url 'panel:company_change_messages' company.slug %}">{% trans "Update messages" %}</a>
              <a class="dropdown-item" href="{% url 'panel:company_change_links' company.slug %}">{% trans "Update links" %}</a>
            </div>
          </li>
        {% endif %}
        {% if request.user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:phone_list' %}">{% trans "Phones" %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'panel:service_list' %}">{% trans "Services" %}</a>
          </li>
        {% endif %}

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarAccount" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user }}
          </a>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarAccount">
            {% if request.user.is_staff %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'accounts:account_detail' %}">{% trans "Profile" %}</a>
            <a class="dropdown-item" href="{% url 'accounts:account_password_change' %}">{% trans "Change password" %}</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:account_logout' %}">{% trans "Logout" %}</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
{% endblock navigation %}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% block breadcrumb %}
        {% if company %}
          <li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
          {% if company.parent_company %}
          <li class="breadcrumb-item"><a href="{{ company.parent_company.get_absolute_url }}">{{ company.parent_company }}</a></li>
          {% endif %}
          <li class="breadcrumb-item active" aria-current="page">{{ company }}</li>
        {% else %}
          <li class="breadcrumb-item active" aria-current="page">{% trans "Dashboard" %}</li>
        {% endif %}
      {% endblock breadcrumb %}
    </ol>
  </nav>

  {% bootstrap_messages %}

  {% if company and not company.link_set.exists %}
  <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 px-4 py-1 rounded relative mt-4" role="alert">
    <strong class="font-semibold">You need to setup your links.</strong>
    <span class="block sm:inline hover:underline">Please <a href="#">click here.</a></span>
  </div>
{%endif%}

<!-- Check if sender from phone -->
{% if company and not company.sender %}
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-1 rounded relative mt-3" role="alert">
    <strong class="font-semibold">Company must have a sender phone,</strong>
    <span class="block sm:inline hover:underline">Please <a href="#">contact support.</a></span>
  </div>
{%endif%}

{% comment %} INFO COMPANY {% endcomment %}
  {% block content_inner %}
  {% comment %} for user in company and not company parent {% endcomment %}
    {% if company and not company.parent_company %}
      <h3 class="mt-5 mb-3">Child companies</h3>

      <div class="row">
        {% for company in company.company_set.all %}
          <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ company }}</h5>
                <a class="btn btn-primary" href="{{ company.get_absolute_url }}">{% trans "Go" %}</a>
              </div>
            </div>
          </div>
        {% endfor %}

        <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% trans "Add child company" %}</h5>
              <a class="btn btn-primary" href="{% url 'panel:company_add' company.slug %}">{% trans "Add" %}</a>
            </div>
          </div>
          <div class="card mt-4">
            <div class="card-body">
              <h5 class="card-title">{% trans "Add Product Item" %}</h5>
              <a class="btn btn-primary" href="{% url 'panel:product_add' company.slug %}">{% trans "Add" %}</a>
            </div>
          </div>
        </div>
      </div>

{% comment %} for user staff or admin {% endcomment %}
    {% elif request.user.is_staff %}
      <h3 class="mb-3">Companies</h3>

      <div class="row">
        {% for company in object_list %}
          <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ company }}</h5>
                <a class="btn btn-primary" href="{{ company.get_absolute_url }}">{% trans "Go" %}</a>
              </div>
            </div>
          </div>
        {% endfor %}

        <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">{% trans "Add company" %}</h5>
              <a class="btn btn-primary" href="{% url 'panel:company_add' %}">{% trans "Add" %}</a>
            </div>
          </div>
        </div>
      </div>
    {% comment %} for user that are not assign as owner but indeed as collab {% endcomment %}
    {% elif not company %}
      <h3 class="mb-3">Companies</h3>

      <div class="row">
        {% for collaborator in request.user.collaborator_set.parent %}
          {% with collaborator.company as company %}
            <div class="col-12 col-sm-10 col-md-6 col-lg-4 mb-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ company }}</h5>
                  <a class="btn btn-primary" href="{{ company.get_absolute_url }}">{% trans "Go" %}</a>
                </div>
              </div>
            </div>
          {% endwith %}
        {% endfor %}
      </div>
    {% endif %}
  {% endblock content_inner %}
</div>
{% endblock content %}

panel/templates/panel/layout.html
{% load i18n static tz %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_timezone as TIME_ZONE %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}" tz="{{ TIME_ZONE }}">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    {% if stripe_public_key %}
    <meta name="spk" content="{{stripe_public_key}}">
    {% endif %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '@fortawesome/fontawesome-free/css/all.min.css' %}">
    {% block css %}{% endblock css %}
    <link rel="stylesheet" href="{% static 'panel/css/panel.css' %}">

    <title>{% block title %}Taypa!{% endblock title %}</title>
  </head>
  <body>
    {% block content %}{% endblock content %}

    <script src="{% url 'javascript-catalog' %}"></script>
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static '@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'panel/js/inlines.js' %}"></script>
    {% block scripts %}{% endblock scripts %}
  </body>
</html>