panel/urls.py
from panel.views.phone import PhoneConnectView
from django.urls import include, path

from . import views


app_name = 'panel'

urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'account/',
        include([
            path(
                '',
                views.AccountDetailView.as_view(),
                name='account_detail'
            ),
            path(
                'change/',
                views.AccountChangeView.as_view(),
                name='account_change'
            ),
            path(
                'login/',
                views.LoginView.as_view(),
                name='account_login'
            ),
            path(
                'logout/',
                views.LogoutView.as_view(),
                name='account_logout'
            ),
            path(
                'password/',
                views.PasswordChangeView.as_view(),
                name='account_password_change'
            ),
            path(
                'password-reset/',
                views.PasswordResetView.as_view(),
                name='account_password_reset'
            ),
            path(
                'password-reset/done/',
                views.PasswordResetDoneView.as_view(),
                name='account_password_reset_done'
            ),
            path(
                'password-reset/<uidb64>/<token>/',
                views.PasswordResetConfirmView.as_view(),
                name='account_password_reset_confirm'
            ),
            path(
                'password-reset/complete/',
                views.PasswordResetCompleteView.as_view(),
                name='account_password_reset_complete'
            ),
        ])
    ),
    path(
        'company/',
        views.CompanyCreateView.as_view(),
        name='company_add'
    ),
    path(
        'phones/',
        include([
            path(
                '',
                views.PhoneListView.as_view(),
                name='phone_list'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.PhoneChangeView.as_view(),
                        name='phone_change'
                    ),
                    path(
                        'connect/',
                        views.PhoneConnectView.as_view(),
                        name='phone_connect'
                    ),
                    path(
                        'delete/',
                        views.PhoneDeleteView.as_view(),
                        name='phone_delete'
                    )
                ])
            ),
            path(
                'purchase/',
                views.PhonePurchaseView.as_view(),
                name='phone_purchase'
            ),
            path(
                'search/',
                views.PhoneSearchView.as_view(),
                name='phone_search'
            ),
            path(
                'sync/',
                views.PhoneSyncView.as_view(),
                name='phone_sync'
            )
        ])
    ),
    path(
        'services/',
        include([
            path(
                '',
                views.ServiceListView.as_view(),
                name='service_list'
            ),
            path(
                'add/',
                views.ServiceCreateView.as_view(),
                name='service_add'
            ),
            path(
                '<int:pk>/',
                include([
                    path(
                        'change/',
                        views.ServiceUpdateView.as_view(),
                        name='service_change'
                    ),
                    path(
                        'delete/',
                        views.ServiceDeleteView.as_view(),
                        name='service_delete'
                    )
                ])
            )
        ])
    ),
    path(
        '<company>/',
        include([
            path(
                '',
                views.IndexView.as_view(),
                name='index'
            ),
            path(
                'add/',
                views.CompanyChildCreateView.as_view(),
                name='company_add'
            ),
            path(
                'change/',
                include([
                    path(
                        '',
                        views.CompanyUpdateView.as_view(),
                        name='company_change'
                    ),
                    path(
                        'messages/',
                        views.CompanyUpdateMessagesView.as_view(),
                        name='company_change_messages'
                    ),
                    path(
                        'links/',
                        views.CompanyUpdateLinksView.as_view(),
                        name='company_change_links'
                    )
                ])
            ),
            path(
                'customers/',
                include([
                    path(
                        '',
                        views.CustomerListView.as_view(),
                        name='customer_list'
                    ),
                    path(
                        'add/',
                        views.CustomerCreateView.as_view(),
                        name='customer_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CustomerDetailView.as_view(),
                                name='customer_detail'
                            ),
                            path(
                                'change/',
                                views.CustomerUpdateView.as_view(),
                                name='customer_change'
                            ),
                            path(
                                'delete/',
                                views.CustomerDeleteView.as_view(),
                                name='customer_delete'
                            ),
                            path(
                                'send-sms/',
                                views.CustomerSendSMSView.as_view(),
                                name='customer_send_sms'
                            )
                        ])
                    ),

                ])
            ),
            path(
                'products/',
                include([
                    path(
                        '',
                        views.ProductListView.as_view(),
                        name='product_list'
                    ),
                    path(
                        'add/',
                        views.ProductCreateView.as_view(),
                        name='product_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.ProductDetailView.as_view(),
                                name='product_detail'
                            ),
                            path(
                                'change/',
                                views.ProductUpdateView.as_view(),
                                name='product_change'
                            ),
                            path(
                                'delete/',
                                views.ProductDeleteView.as_view(),
                                name='product_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'category/',
                include([
                    path(
                        '',
                        views.CategoryListView.as_view(),
                        name='category_list'
                    ),
                    path(
                        'add/',
                        views.CategoryCreateView.as_view(),
                        name='category_add'
                    ),
                    path(
                        '<int:pk>/',
                        include([
                            path(
                                '',
                                views.CategoryDetailView.as_view(),
                                name='category_detail'
                            ),
                            path(
                                'change/',
                                views.CategoryUpdateView.as_view(),
                                name='category_change'
                            ),
                            path(
                                'delete/',
                                views.CategoryDeleteView.as_view(),
                                name='category_delete'
                            ),
                        ])
                    ),
                ])
            ),
            path(
                'ordenes/',
                include([
                    path(
                        '',
                        views.OrderListView.as_view(),
                        name='order_list'
                    ),
                        ])
            ),
            path(
                'feedbacks/',
                include([
                    path(
                        '',
                        views.FeedbackListView.as_view(),
                        name='feedback_list'
                    ),
                    path(
                        '<int:pk>/',
                        views.FeedbackDetailView.as_view(),
                        name='feedback_detail'
                    )
                ])
            ),
            path(
                'messages/',
                include([

taypa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from django.urls import include, path

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('taypa.api.urls')),
    path(
        'jsi18n/',
        JavaScriptCatalog.as_view(),
        name='javascript-catalog'
    ),
    path('panel/', include('panel.urls')),
    path('accounts/', include('accounts.urls')),
    path('billing-profile/', include('billing_profiles.urls')),
    path('', include('public.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )


handler400 = 'panel.views.error.pag_400_bad_request'
handler403 = 'panel.views.error.pag_403_forbidden'
handler404 = 'panel.views.error.pag_404_not_found'
handler500 = 'panel.views.error.pag_500_error_server'

panel/forms/category.py
from itertools import product
from django import forms

from core.models import Category, Product

def get_category_form(company):

    class CategoryForm(forms.ModelForm):
        
        products = forms.ModelMultipleChoiceField(
            queryset=Product.objects.filter(company=company)
            )

        class Meta:
            exclude = (
                'company',
            )
            model = Category

    return CategoryForm

panel/views/base.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from core.models import Company
from core.views import CompanyMixin

class IndexView(CompanyMixin, LoginRequiredMixin, ListView):
    model = Company
    template_name = 'panel/index.html'

    def get_queryset(self):
        queryset = super().get_queryset().filter(
            parent_company__isnull=True
        )

        if not self.request.user.is_staff:
            queryset = queryset.none()
        
        return queryset

    def get(self, request, *args, **kwargs):
        if not request.user.is_staff and not self.company:
            queryset = request.user.collaborator_set.filter(
                company__parent_company__isnull=True
            )

            if queryset.count() == 1:
                collaborator = queryset.get()
                company = collaborator.company
                return HttpResponseRedirect(company.get_absolute_url())
                   
        return super().get(request, *args, **kwargs)

panel/views/category.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView, DeleteView, DetailView, UpdateView
)
from django_filters.views import FilterView

from core.models import Category

from core.views import (
    CompanyCreateMixin,
    CompanyQuerySetMixin
)
from ..filters.category import CategoryFilterSet
from ..forms.category import get_category_form

class CategoryCreateView(CompanyCreateMixin, CreateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

class CategoryDeleteView(CompanyQuerySetMixin, DeleteView):
    model = Category
    template_name = 'panel/category/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('panel:category_list', args=[self.company.slug])

class CategoryDetailView(CompanyQuerySetMixin, DetailView):
    model = Category
    template_name = 'panel/category/detail.html'

class CategoryListView(CompanyQuerySetMixin, FilterView):
    template_name = 'panel/category/list.html'
    filterset_class = CategoryFilterSet
    model = Category
    paginate_by = 30
    ordering = ['-id']  
class CategoryUpdateView(CompanyQuerySetMixin, UpdateView):
    model = Category
    template_name = 'panel/category/form.html'

    def get_form_class(self):
        return get_category_form(self.company)

    def get_success_url(self):
        return reverse_lazy(
            'panel:category_detail',
            args=[self.company.slug, self.object.id]
        )

panel/views/company.py
from boilerplate.mixins import ExtraFormsAndFormsetsMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, UpdateView

from core.models import Company
from core.views import (
    CompanyCreateMixin,
    CollaboratorRequiredMixin,
    UserCreateMixin
)
from ..forms.company import (
    CompanyForm,
    CompanyChildForm,
    CompanyEmptyForm,
    CompanyLinkFormSet,
    CompanyMessagesForm
)

class CompanyCreateView(PermissionRequiredMixin, CreateView):
    form_class = CompanyForm
    model = Company
    permission_required = 'core:add_company'
    template_name = 'panel/company/form.html'

class CompanyChildCreateView(
    CompanyCreateMixin, UserCreateMixin, CreateView
):
    company_field = 'parent_company'
    form_class = CompanyChildForm
    model = Company
    template_name = 'panel/company/form.html'

class CompanyUpdateView(
    CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyChildForm
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

class CompanyUpdateLinksView(
    ExtraFormsAndFormsetsMixin, CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyEmptyForm
    formset_list = (
        CompanyLinkFormSet,
    )
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

class CompanyUpdateMessagesView(
    CollaboratorRequiredMixin, UpdateView
):
    form_class = CompanyMessagesForm
    model = Company
    template_name = 'panel/company/form.html'
    slug_url_kwarg = 'company'

panel/views/error.py
from django.shortcuts import render

#400: peticion invalida
def pag_400_bad_request(request, exception):
    response = render(request, '400.html')
    response.status_code=400
    return response

#403: peticion prohibida
def pag_403_forbidden(request, exception):
    response = render(request, '403.html')
    response.status_code=403
    return response

#404: página no encontrada
def pag_404_not_found(request, exception):
    response = render(request, '404.html')
    response.status_code = 404
    return response

#500: error en el servidor
def pag_500_error_server(request):
    response = render(request, '500.html')
    response.status_code=500
    return response

panel/views/feedback.py
from django.views.generic import DetailView
from django_filters.views import FilterView

from core.views import CompanyQuerySetMixin
from core.models import Feedback
from ..filters.feedback import FeedbackFilterSet


class FeedbackDetailView(CompanyQuerySetMixin, DetailView):
    model = Feedback
    template_name = 'panel/feedback/detail.html'


class FeedbackListView(CompanyQuerySetMixin, FilterView):
    filterset_class = FeedbackFilterSet
    model = Feedback
    paginate_by = 30
    template_name = 'panel/feedback/list.html'

panel/views/message.py
from django.views.generic import DetailView
from django_filters.views import FilterView

from core.models import Message
from core.views import CompanyQuerySetMixin
from ..filters.message import MesageFilterSet
class MessageDetailView(CompanyQuerySetMixin, DetailView):
    model = Message
    template_name = 'panel/message/detail.html'

class MessageListView(CompanyQuerySetMixin, FilterView):
    filterset_class = MesageFilterSet
    model = Message
    paginate_by = 30
    template_name = 'panel/message/list.html'

panel/templates/panel/product/confirm_delete.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
{% if company.parent_company %}
<li class="breadcrumb-item"><a href="{{ company.parent_company.get_absolute_url }}">{{ company.parent_company }}</a></li>
{% endif %}
<li class="breadcrumb-item"><a href="{{ company.get_absolute_url }}">{{ company }}</a></li>
<li class="breadcrumb-item"><a href="{% url 'panel:customer_list' company.slug %}">{% trans "Customers" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "Delete" %} {{ object }}</li>
{% endblock breadcrumb %}

{% block content_inner %}
  {% include 'panel/_snippets/confirm_delete.html' %}
{% endblock content_inner %}

panel/templates/panel/product/detail.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
{% if company.parent_company %}
<li class="breadcrumb-item"><a href="{{ company.parent_company.get_absolute_url }}">{{ company.parent_company }}</a></li>
{% endif %}
<li class="breadcrumb-item"><a href="{{ company.get_absolute_url }}">{{ company }}</a></li>
<li class="breadcrumb-item"><a href="{% url 'panel:customer_list' company.slug %}">{% trans "Customers" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ object }}</li>
{% endblock breadcrumb %}

{% block content_inner %}
<div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{{ object }}</h2>
    <div>
      <a class="btn btn-success" href="{% url 'panel:product_change' company.slug object.id %}"><i class="fas fa-edit"></i> {% trans "Change" %}</a>
      <a class="btn btn-danger" href="{% url 'panel:product_delete' company.slug object.id %}"><i class="fas fa-trash"></i> {% trans "Delete" %}</a>
    </div>
  </div>

  <div class="card" style="width: 18rem;">
    {% if object.image %}
    <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap {{object.title}}" width="286" height="180">
    {% endif %}

    <div class="card-body">
      <h5 class="card-title">{{object.title}}</h5>

      <div class="h5 font-weight-bold">
        Precio: <span class="text-warning">${{object.price}}</span>
      </div>

      <div class="h4">
        <p>{{object.description}}</p>
      </div>

      <div class="h4">
        Disponible: <i class="fas fa-{{ object.available|yesno:'check,times' }} text-{{ object.available|yesno:'success,danger' }}"></i>
      </div>

    </div>
  </div>

{% endblock content_inner %}

panel/templates/panel/product/form.html
{% extends 'panel/index.html' %}

{% load i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
{% if company.parent_company %}
<li class="breadcrumb-item"><a href="{{ company.parent_company.get_absolute_url }}">{{ company.parent_company }}</a></li>
{% endif %}
<li class="breadcrumb-item"><a href="{{ company.get_absolute_url }}">{{ company }}</a></li>
<li class="breadcrumb-item"><a href="{% url 'panel:customer_list' company.slug %}">{% trans "Customers" %}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% if object %}{% trans "Change" %} {{ object }}{% else %}{% trans "Add" %}{% endif %}</li>
{% endblock breadcrumb %}

{% block content_inner %}
  <div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{% if object %}{{ object }}{% else %}{% trans "Add customer" %}{% endif %}</h2>
  </div>

  {% include 'panel/_snippets/form.html' with layout="horizontal" %}
{% endblock content_inner %}

panel/templates/panel/product/list.html
{% extends 'panel/index.html' %}

{% load bootstrap4 i18n %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'panel:index' %}">{% trans "Dashboard" %}</a></li>
{% if company.parent_company %}
<li class="breadcrumb-item"><a href="{{ company.parent_company.get_absolute_url }}">{{ company.parent_company }}</a></li>
{% endif %}
<li class="breadcrumb-item"><a href="{{ company.get_absolute_url }}">{{ company }}</a></li>
<li class="breadcrumb-item active" aria-current="page">{% trans "products" %}</li>
{% endblock breadcrumb %}

{% block content_inner %}
  <div class="align-items-center d-flex justify-content-between mb-3">
    <h2>{% trans "Products" %}</h2>
    <a class="btn btn-primary" href="{% url 'panel:product_add' company.slug %}"><i class="fas fa-plus"></i> {% trans "Add" %}</a>
  </div>

  {% include 'panel/_snippets/filter.html' %}

  <div class="table-responsive">
    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>{% trans "Image" %}</th>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Price" %}</th>
          <th>{% trans "Available" %}</th>
          <th>{% trans "In Stock" %}</th>
          <th class="text-right">{% trans "Actions" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
        <tr>
          <th>
            {% if object.image %}
            <img class="card-img-top" src="{{ object.image.url }}" alt="Card image cap {{object.title}}" width="60" height="60">
            {% endif %}
          </th>
          <th><a href="{% url 'panel:product_detail' company.slug object.id %}">{{ object.title }}</a></th>
          <td>{{ object.price }}</td>
          <td><i class="fas fa-{{ object.available|yesno:'check,times' }} text-{{ object.available|yesno:'success,danger' }}"></i></td>
          <td>{{ object.stock|default:'' }}</td>
          <td class="text-right">
            <a class="btn btn-sm btn-success" href="{% url 'panel:product_change' company.slug object.id %}"><i class="fas fa-edit"></i> {% trans "Change" %}</a>
            <a class="btn btn-sm btn-danger" href="{% url 'panel:product_delete' company.slug object.id %}"><i class="fas fa-trash"></i> {% trans "Delete" %}</a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td class="text-center text-muted" colspan="5">
            {% trans "No information." %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% bootstrap_pagination page_obj extra=request.GET.urlencode %}
{% endblock content_inner %}